conflicts merged

diff --git a/bin/manage_variants b/bin/manage_variants
--- a/bin/manage_variants
+++ b/bin/manage_variants
@@ -6,7 +6,7 @@ declare variants=$2
 declare -r OS=$(uname -s)
 
 # File format example
-# 1.10.2	unstable	gcc/4.8.5
+# openmpi/1.10.2	unstable	gcc/4.8.5
 declare -a toks=()
 declare version=''
 declare release=''
@@ -22,7 +22,7 @@ while read -a toks; do
 
 	"${buildblock}"  "${module#*/}" --release=${release} "${dependencies[@]/#/--with=}"
 	if [[ $? != 0 ]]; then
-		echo "Failed building:  ${version} --release=${release} ${dependencies[@]/#/--with=}" 1>&2
+		echo "Failed building:  ${module} --release=${release} ${dependencies[@]/#/--with=}" 1>&2
 		exit 42
 	fi
 done < "${variants}"
